[tool.project-metadata]
name = "Mist Plugin"
description = "A plugin for the AI assistant app, enhancing it with Mist capabilities."
version = "1.0.5"

[tool.versioning]
major = 1
minor = 0
patch = 5
