name: "mist"

chats:
    custom: xxxxxxxxxxxxxxxxxxxxxx
    default: xxxxxxxxxxxxxxxxxxxxxxxxxx

nac-events:
  NAC_ACCOUNTING_START:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_ACCOUNTING_STOP:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_ACCOUNTING_UPDATE:
    web: false
    sql: false
    syslog: false
    teams: false

  NAC_SESSION_STARTED:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_SESSION_ENDED:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_CLIENT_PERMIT:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_CLIENT_DENY:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_CLIENT_IP_ASSIGNED:
    web: false
    sql: false
    syslog: false
    teams: false
  
  NAC_CLIENT_CERT_CHECK_SUCCESS:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_CLIENT_CERT_CHECK_FAILURE:
    web: true
    sql: false
    syslog: false
    teams: true
  NAC_CLIENT_CERT_EXPIRED:
    web: true
    sql: false
    syslog: false
    teams: true
  NAC_SERVER_CERT_VALIDATION_SUCCESS:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_SERVER_CERT_VALIDATION_FAILURE:
    web: true
    sql: false
    syslog: false
    teams: false

  NAC_IDP_GROUPS_LOOKUP_SUCCESS:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_IDP_GROUPS_LOOKUP_FAILURE:
    web: true
    sql: false
    syslog: false
    teams: false
  NAC_IDP_AUTHC_SUCCESS:
    web: false
    sql: false
    syslog: false
    teams: false
  
  NAC_CLIENT_COA_REAUTH:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_MDM_LOOKUP_SUCCESS:
    web: false
    sql: false
    syslog: false
    teams: false
  NAC_MDM_DEVICE_NOT_ENROLLED:
    web: true
    sql: false
    syslog: false
    teams: false
  NAC_MDM_LOOKUP_FAILURE:
    web: true
    sql: false
    syslog: false
    teams: false

  default:
    web: true
    sql: false
    syslog: false
    teams: true

client-events:
  user-connect:
    web: false
    sql: false
    syslog: false
    teams: false
  guest-connect:
    web: false
    sql: false
    syslog: false
    teams: false
  disconnect:
    web: false
    sql: false
    syslog: false
    teams: false

  client-info:
    web: false
    sql: false
    syslog: false
    teams: false
  
  default:
    web: true
    sql: false
    syslog: false
    teams: true

device-events:
  GW_ALARM:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_MISTWA_CONFIGURATION_CLASH:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_CONFIG_CHANGED_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: false   
  GW_CONFIGURED:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_CONFIG_GENERATED:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_CONFIG_FAILED:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_OSPF_NEIGHBOR_DOWN:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_OSPF_NEIGHBOR_UP:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_PORT_UP:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_RECONFIGURED:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_REJECTED:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_RESTART_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_VPN_PATH_DOWN:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_VPN_PATH_UP:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_VPN_PEER_DOWN:
    web: true
    sql: false
    syslog: false
    teams: false
  GW_VPN_PEER_UP:
    web: true
    sql: false
    syslog: false
    teams: false

  SW_ALARM_CHASSIS_PSU:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_CHASSIS_PEM:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_CHASSIS_PEM_CLEAR:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_OPTICS_IFACE_RX_LOW:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_OPTICS_IFACE_SFP_LOW:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_CHASSIS_PSU:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_CHASSIS_POE:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ALARM_CHASSIS_POE_CLEAR:
    web: true
    sql: false
    syslog: false
    teams: true

  SW_BOUNCE_PORT:
    web: true
    sql: false
    syslog: false
    teams: true
    
  SW_CONFIG_CHANGED_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: false
  SW_CONFIG_FAILED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_CONFIG_GENERATED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_CONFIG_ERROR_ADDTL_COMMAND:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_CONFIGURED:
    web: true
    sql: false
    syslog: false
    teams: true

  SW_CONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true

  SW_DDOS_PROTOCOL_VIOLATION_SET:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_DDOS_PROTOCOL_VIOLATION_CLEAR:
    web: true
    sql: false
    syslog: false
    teams: true

  SW_DOT1XD_USR_AUTHENTICATED:
    web: false
    sql: false
    syslog: false
    teams: false
  SW_DOT1XD_USR_ON_SRVR_REJECT_VLAN:
    web: true
    sql: false
    syslog: false
    teams: false
  SW_DOT1XD_USR_SESSION_DISCONNECTED:
    web: false
    sql: false
    syslog: false
    teams: false
  SW_DOT1XD_USR_SESSION_HELD:
    web: true
    sql: false
    syslog: false
    teams: false
    
  SW_LACP_RX_STALE:
    web: true
    sql: false
    syslog: false
    teams: false
  SW_MAC_LIMIT_RESET:
    web: true
    sql: false
    syslog: false
    teams: false

  SW_PORT_DOWN:
    web: false
    sql: false
    syslog: false
    teams: false
  SW_PORT_UP:
    web: false
    sql: false
    syslog: false
    teams: false
  SW_IP_CONFLICT:
    web: true
    sql: false
    syslog: false
    teams: true
    
  SW_DISCONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_DYNAMIC_PORT_ASSIGNED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_PORT_BPDU_BLOCKED:
    web: true
    sql: false
    syslog: false
    teams: true  
  SW_RADIUS_SERVER_UNRESPONSIVE:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_RECONFIGURED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_RECOVERY_SNAPSHOT_REQUESTED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_RECOVERY_SNAPSHOT_SUCCEEDED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_REJECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_RESTART_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_RESTARTED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_STP_TOPO_CHANGED:
    web: true
    sql: false
    syslog: false
    teams: true
  
  SW_UPGRADE_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_UPGRADE_FAILED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_UPGRADE_PENDING:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_UPGRADE_STORAGE_CLEANUP:
    web: false
    sql: false
    syslog: false
    teams: true
  SW_UPGRADE_IMAGE_UPLOADED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_UPGRADE_SOFTWARE_ADD:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_UPGRADED:
    web: true
    sql: false
    syslog: false
    teams: true
  
  SW_VC_MASTER_CHANGED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_VC_MEMBER_ADDED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_ZTP_FINISHED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_OSPF_NEIGHBOR_DOWN:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_OSPF_NEIGHBOR_UP:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_BGP_NEIGHBOR_STATE_CHANGED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_BGP_NEIGHBOR_DOWN:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_BGP_NEIGHBOR_UP:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_EVPN_BGP_PEER_STATUS_CHANGE:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_MAC_LIMIT_EXCEEDED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_WARN_OPTICS_IFACE_SFP_LOW:
    web: true
    sql: false
    syslog: false
    teams: true
  
  AP_CONFIG_CHANGED_BY_RRM:
    web: true
    sql: false
    syslog: false
    teams: false
  AP_CONFIG_CHANGED_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: false
  AP_CONFIGURED:
    web: true
    sql: false
    syslog: false
    teams: false
  AP_CONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  AP_DISCONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  AP_DISCONNECTED_V1:
    web: true
    sql: false
    syslog: false
    teams: true
  AP_RECONFIGURED:
    web: true
    sql: false
    syslog: false
    teams: true
  AP_RESTART_BY_USER:
    web: true
    sql: false
    syslog: false
    teams: false
  AP_RESTARTED:
    web: true
    sql: false
    syslog: false
    teams: false
  AP_RRM_ACTION:
    web: true
    sql: false
    syslog: false
    teams: false
  AP_RADAR_DETECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  
  CONNECTIVITY_TEST:
    web: true
    sql: false
    syslog: false
    teams: false
  
  update:
    web: false
    sql: false
    syslog: false
    teams: true

  default:
    web: true
    sql: false
    syslog: false
    teams: true

alarms:
  admin-action:
    web: true
    sql: false
    syslog: false
    teams: true
  ap_bad_cable:
    web: true
    sql: false
    syslog: false
    teams: true
  bad_cable:
    web: true
    sql: false
    syslog: false
    teams: true
  configuration:
    web: true
    sql: false
    syslog: false
    teams: true
  connectivity:
    web: true
    sql: false
    syslog: false
    teams: true

  device_down:
    web: true
    sql: false
    syslog: false
    teams: true
  device_reconnected:
    web: true
    sql: false
    syslog: false
    teams: true
  device_restarted:
    web: true
    sql: false
    syslog: false
    teams: true

  dhcp_failure:
    web: true
    sql: false
    syslog: false
    teams: true
  firmware:
    web: true
    sql: false
    syslog: false
    teams: true

  infra_arp_failure:
    web: false
    sql: false
    syslog: false
    teams: false
  infra_arp_success:
    web: false
    sql: false
    syslog: false
    teams: false
  infra_dhcp_failure:
    web: false
    sql: false
    syslog: false
    teams: false
  infra_dhcp_success:
    web: false
    sql: false
    syslog: false
    teams: false
  infra_dns_failure:
    web: true
    sql: false
    syslog: false
    teams: false
  infra_dns_success:
    web: false
    sql: false
    syslog: false
    teams: false

  missing_vlan:
    web: true
    sql: false
    syslog: false
    teams: true
  rogue_ap:
    web: true
    sql: false
    syslog: false
    teams: true
  rogue_client:
    web: true
    sql: false
    syslog: false
    teams: true

  switch_down:
    web: true
    sql: false
    syslog: false
    teams: true
  switch_reconnected:
    web: true
    sql: false
    syslog: false
    teams: true
  switch_restarted:
    web: true
    sql: false
    syslog: false
    teams: true
  switch_stp_loop:
    web: true
    sql: false
    syslog: false
    teams: true
  
  sw_alarm_chassis_psu:
    web: true
    sql: false
    syslog: false
    teams: true
  sw_alarm_chassis_poe:
    web: true
    sql: false
    syslog: false
    teams: true
  sw_bad_optics:
    web: true
    sql: false
    syslog: false
    teams: true
  sw_bpdu_error:
    web: true
    sql: false
    syslog: false
    teams: true
  
  vc_master_changed:
    web: true
    sql: false
    syslog: false
    teams: true

  default:
    web: true
    sql: false
    syslog: false
    teams: true

audits:
  update:
    web: true
    sql: false
    syslog: false
    teams: true
  webshell:
    web: true
    sql: false
    syslog: false
    teams: false
  mist-login:
    web: true
    sql: false
    syslog: false
    teams: true
  accessed-org:
    web: true
    sql: false
    syslog: false
    teams: true
  restart:
    web: true
    sql: false
    syslog: false
    teams: true
  configuration:
    web: true
    sql: false
    syslog: false
    teams: true
  add-webhook:
    web: true
    sql: false
    syslog: false
    teams: false
  add-nac_label:
    web: true
    sql: false
    syslog: false
    teams: true
  mist-support:
    web: true
    sql: false
    syslog: false
    teams: true
  bounce-port:
    web: true
    sql: false
    syslog: false
    teams: true

  default:
    web: true
    sql: false
    syslog: false
    teams: true

device-updowns:
  SW_DISCONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_CONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  SW_RESTARTED:
    web: true
    sql: false
    syslog: false
    teams: true

  AP_DISCONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  AP_CONNECTED:
    web: true
    sql: false
    syslog: false
    teams: true
  AP_RESTARTED:
    web: true
    sql: false
    syslog: false
    teams: true

  default:
    web: true
    sql: false
    syslog: false
    teams: true

location:
  default:
    web: true
    sql: false
    syslog: false
    teams: false

occupancy-alerts:
  default:
    web: true
    sql: false
    syslog: false
    teams: false

rssizone:
  default:
    web: true
    sql: false
    syslog: false
    teams: false

sdkclient-scan-data:
  default:
    web: true
    sql: false
    syslog: false
    teams: false

vbeacon:
  default:
    web: true
    sql: false
    syslog: false
    teams: false

zone:
  default:
    web: true
    sql: false
    syslog: false
    teams: false
