# Definitions to parse device events from Mist webhooks
# A list of device events that can be parsed from Mist webhooks.
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.
# - severity: The severity of the event, which can be "debug", "info" "warning", "error", or "critical".


# Switch Events
SW_CONNECTED:
  description: "A switch has connected to the Mist cloud"
  message: "{self.device_name} at {self.site_name} has connected to the Mist cloud"
  severity: "info"

SW_DISCONNECTED:
  description: "A switch has disconnected from the Mist cloud (reboot, internet outage, upstream failure, etc.)"
  message: "{self.device_name} at {self.site_name} has disconnected from the Mist cloud"
  severity: "warning"

SW_PORT_DOWN:
  description: "Switch port down event"
  message: "Switch port {self.port_id} on {self.device_name} at {self.site_name} has gone down"
  severity: "info"

SW_PORT_UP:
  description: "Switch port up event"
  message: "Switch port {self.port_id} on {self.device_name} at {self.site_name} has come up"
  severity: "debug"

SW_IP_CONFLICT:
  description: "An IP address conflict has been detected on a switch port"
  message: "IP conflict detected on switch {self.device_name}, port {self.port_id} at {self.site_name}: {self.text}"
  severity: "warning"

SW_DHCP_POOL_EXHAUSTED:
  description: "A DHCP pool on a switch has been exhausted, which means that there are no more available IP addresses to assign to clients"
  message: "DHCP pool exhausted on switch {self.device_name} at {self.site_name}: {self.text}"
  severity: "warning"

SW_DOT1XD_USR_AUTHENTICATED:
  description: "A dot1x user has been authenticated"
  message: "Dot1x user on switch {self.device_name}, port {self.port_id} at {self.site_name} has been authenticated"
  severity: "debug"

SW_DOT1XD_USR_SESSION_DISCONNECTED:
  description: "A dot1x user session has been disconnected"
  message: "Dot1x user on switch {self.device_name}, port {self.port_id} at {self.site_name} has disconnected"
  severity: "debug"

SW_DOT1XD_USR_ON_SRVR_REJECT_VLAN:
  description: "A user failed to authenticated, and was places on the server reject VLAN"
  message: "Dot1x user on switch {self.device_name}, port {self.port_id} at {self.site_name} has been placed on the server reject VLAN"
  severity: "warning"

SW_DOT1XD_USR_SESSION_HELD:
  description: ""
  message: "{self.text}\n Switch {self.device_name}, site {self.site_name}"
  severity: "warning"

SW_ALARM_OPTICS_IFACE_SFP_LOW:
  description: "A switch has detected a low optical signal on an SFP interface"
  message: "{self.device_name} at {self.site_name}: {self.text}"
  teams: "{self.device_name} at {self.site_name} is reporting low SFP power on {self.port_id} (Alarm)"
  severity: "warning"

SW_WARN_OPTICS_IFACE_SFP_LOW:
  description: "A switch has detected a low optical signal on an SFP interface"
  message: "{self.device_name} at {self.site_name}: {self.text}"
  teams: "{self.device_name} at {self.site_name} is reporting low SFP power on {self.port_id} (Warning)"
  severity: "info"

SW_LACP_RX_STALE:
  description: "LACP messages have not been received from a switch port recently"
  message: "{self.device_name} at {self.site_name} has reported an LACP issue.\n {self.text}"
  severity: "warning"

SW_MAC_LIMIT_RESET:
  description: ""
  message: "{self.device_name} at {self.site_name} has {self.text}"
  severity: "warning"

SW_BGP_NEIGHBOR_STATE_CHANGED:
  description: "A BGP neighbour has changed state (eg, Established, Idle, Active, etc.)"
  message: "{self.device_name} at {self.site_name} has changed BGP neighbour state:\n {self.text}"
  severity: "warning"

SW_BGP_NEIGHBOR_DOWN:
  description: "A BGP neighbour has gone down (changed to Idle)"
  message: "{self.device_name} at {self.site_name} lost a BGP peer:\n {self.text}"
  severity: "error"

SW_BGP_NEIGHBOR_UP:
  description: "A BGP neighbour has come up (established)"
  message: "{self.device_name} at {self.site_name} has a new BGP neighbour:\n {self.text}"
  severity: "warning"

SW_EVPN_BGP_PEER_STATUS_CHANGE:
  description: "A BGP peer with the EVPN family has changed status"
  message: "{self.device_name} at {self.site_name} has changed BGP/EVPN neighbour state:\n {self.text}"
  severity: "warning"

SW_CONFIG_CHANGED_BY_USER:
  description: "The configuration of a switch has been changed by an administrator; There is very little information available in the webhook"
  message: "{self.device_name} at {self.site_name} has had its configuration changed by an administrator"
  severity: "info"

SW_CONFIG_ERROR_ADDTL_COMMAND:
  description: "A command in the 'additional commands' section of the Mist web UI has failed"
  message: "A configuration item in the 'additional commands' section of the Mist web UI has failed on {self.device_name} at {self.site_name}:\n {self.text}"
  severity: "info"

SW_CONFIGURED:
  description: "A switch has been configured and the commit is complete"
  message: "Config push on {self.device_name} at {self.site_name} has been completed\n {self.text}"
  severity: "info"

SW_CONFIG_FAILED:
  description: "A switch configuration has failed, which means that the commit did not complete successfully"
  message: "Config push on {self.device_name} at {self.site_name} has failed\n {self.text}"
  severity: "error"

SW_ALARM_CHASSIS_POE:
  description: "A switch has detected a chassis PoE alarm, which means that the PoE budget is exceeded or there is a PoE failure"
  message: "{self.device_name} at {self.site_name} has a PoE alarm on {self.port_id}"
  severity: "warning"

SW_ALARM_CHASSIS_POE_CLEAR:
  description: "A PoE alarm on a switch has cleared"
  message: "{self.device_name} at {self.site_name} has cleared the PoE alarm on {self.port_id}"
  severity: "info"

SW_DDOS_PROTOCOL_VIOLATION_SET:
  description: "The DDoS threshold has been exceeded, and the switch is blocking traffic to prevent a DDoS attack"
  message: "{self.device_name} at {self.site_name} has exceeded the DDoS threshold.\n {self.text}"
  severity: "warning"

SW_DDOS_PROTOCOL_VIOLATION_CLEAR:
  description: "The DDoS threshold has been cleared, and the switch is no longer blocking traffic"
  message: "Traffic on {self.device_name} at {self.site_name} has returned to normal after a DDoS threshold violation.\n {self.text}"
  severity: "info"

SW_STP_TOPO_CHANGED:
  description: "The Spanning Tree Protocol (STP) topology has changed, which means that a port has gone down or up, or a new root bridge has been elected"
  message: "{self.device_name} at {self.site_name} has detected an STP topology change:\n {self.text}"
  severity: "warning"

SW_RADIUS_SERVER_UNRESPONSIVE:
  description: "A RADIUS server is unresponsive, which means that authentication requests are not being processed"
  message: "{self.device_name} at {self.site_name} has detected an unresponsive RADIUS server:\n {self.text}"
  severity: "warning"

SW_MAC_LIMIT_EXCEEDED:
  description: "The MAC limit has been exceeded on a switch port, which means that too many MAC addresses have been learned"
  message: "{self.device_name} at {self.site_name} has exceeded the MAC limit on {self.port_id}:\n {self.text}"
  severity: "warning"

SW_OSPF_NEIGHBOR_UP:
  description: "An OSPF neighbour has come up, which means that a new OSPF adjacency has been established"
  message: "{self.device_name} at {self.site_name} has established an OSPF neighbour:\n {self.text}"
  severity: "info"

SW_OSPF_NEIGHBOR_DOWN:
  description: "An OSPF neighbour has gone down"
  message: "{self.device_name} at {self.site_name} has lost an OSPF neighbour:\n {self.text}"
  severity: "info"

SW_OSPF_NEIGHBOR_ADJACENCY_FAILED:
  description: "An OSPF neighbour adjacency has timed out or failed"
  message: "{self.device_name} at {self.site_name} has lost an OSPF neighbour:\n {self.text}"
  severity: "info"

SW_RESTART_BY_USER:
  description: "A switch has been restarted by an administrator"
  message: "{self.device_name} at {self.site_name} has been restarted by an administrator"
  severity: "info"

SW_UPGRADED:
  description: "A switch has been upgraded to a new firmware version"
  message: "{self.device_name} at {self.site_name} has been upgraded to version {self.version}"
  severity: "info"

SW_PORT_BPDU_BLOCKED:
  description: "A switch port has been blocked due to a BPDU error"
  message: "{self.device_name} at {self.site_name} has blocked port {self.port_id} due to a BPDU error"
  severity: "warning"

SW_BOUNCE_PORT:
  description: "A switch port has been bounced, which means that it has been shut down and then brought back up"
  message: "{self.port_id} bounced on {self.device_name} at {self.site_name}"
  severity: "info"

SW_ALARM_CHASSIS_PEM:
  description: "PEM issues, fault slot, high CPU, issues with CB, PoE, and so on."
  message: "{self.device_name} at {self.site_name} has a PEM alarm: {self.text}"
  severity: "warning"

SW_ALARM_CHASSIS_PEM_CLEAR:
  description: "Resolved a PEM issue, fault slot, high CPU, issues with CB, PoE, and so on."
  message: "{self.device_name} at {self.site_name} has cleared a PEM alarm. Original error: {self.text}"
  severity: "warning"


# Access Point Events
AP_RESTARTED:
  description: "An access point has restarted (update, failure, etc.)"
  message: "{self.ap_name} at {self.site_name} has restarted: ({self.reason})"
  severity: "warning"

AP_RESTART_BY_USER:
  description: "An access point has been restarted by an admin"
  message: "{self.ap_name} at {self.site_name} has been restarted by an administrator"
  severity: "info"

AP_CONNECTED:
  description: "An AP has connected to the Mist cloud"
  message: "{self.ap_name} at {self.site_name} has connected to the Mist cloud"
  severity: "info"

AP_DISCONNECTED:
  description: "An AP has disconnected from the Mist cloud (reboot, internet outage, upstream failure, etc.)"
  message: "{self.ap_name} at {self.site_name} has disconnected from the Mist cloud"
  severity: "warning"

AP_CONFIGURED:
  description: "An AP has been configured"
  message: "{self.ap_name} at {self.site_name} has been configured"
  severity: "info"

AP_CONFIG_CHANGED_BY_USER:
  description: "A template has been changed, which has caused the configuration of an AP to change"
  message: "An administrator updated a template, which has changed the configuration of {self.ap_name} at {self.site_name}"
  severity: "info"

AP_CONFIG_CHANGED_BY_RRM:
  description: "RRM has tuned the configuration of an AP (e.g., power, channel)"
  message: "The config of {self.ap_name} at {self.site_name} has been tuned by RRM"
  severity: "debug"

AP_CERT_REGENERATED:
  description: "An AP certificate has been regenerated"
  message: "{self.ap_name} at {self.site_name} has regenerated its certificate"
  severity: "info"

AP_RRM_ACTION:
  description: "RRM (Radio Resource Management) has taken an action on an AP. There could be interference, radars, etc, and it needs to be tuned"
  message: "RRM action on {self.ap_name} at {self.site_name}"
  severity: "info"

AP_RADAR_DETECTED:
  description: "A radar has been detected by an AP, and it has been tuned to avoid interference. An AP will always yield to a radar"
  message: "A radar has been detected by {self.ap_name} in the vicinity of {self.site_name}. Channels have been adjusted according to legal requirements"
  severity: "warning"

AP_UPGRADE_FAILED:
  description: "An AP firmware upgrade has failed"
  message: "{self.ap_name} at {self.site_name} has failed to upgrade. Reason: {self.reason}. {self.text}"
  severity: "error"


# Gateway Events
GW_ALARM:
  description: ""
  message: "devices/GW_ALARM: {self.event}"
  severity: "info"

GW_MISTWA_CONFIGURATION_CLASH:
  description: ""
  message: "devices/GW_MISTWA_CONFIGURATION_CLASH: {self.event}"
  severity: "info"

AP_CONFIG_CHANGED_BY_USER:
  description: "A template has been changed, which has caused the configuration of a gateway to change"
  message: "An administrator updated a template, which has changed the configuration of {self.device_name} at {self.site_name}"
  severity: "info"

GW_CONFIGURED:
  description: ""
  message: "devices/GW_CONFIGURED: {self.event}"
  severity: "info"

GW_CONFIG_GENERATED:
  description: ""
  message: "devices/GW_CONFIG_GENERATED: {self.event}"
  severity: "info"

GW_CONFIG_FAILED:
  description: ""
  message: "devices/GW_CONFIG_FAILED: {self.event}"
  severity: "info"

GW_OSPF_NEIGHBOR_DOWN:
  description: ""
  message: "devices/GW_OSPF_NEIGHBOR_DOWN: {self.event}"
  severity: "info"

GW_OSPF_NEIGHBOR_UP:
  description: ""
  message: "devices/GW_OSPF_NEIGHBOR_UP: {self.event}"
  severity: "info"

GW_PORT_UP:
  description: ""
  message: "devices/GW_PORT_UP: {self.event}"
  severity: "info"

GW_RECONFIGURED:
  description: ""
  message: "devices/GW_RECONFIGURED: {self.event}"
  severity: "info"

GW_REJECTED:
  description: ""
  message: "devices/GW_REJECTED: {self.event}"
  severity: "info"

GW_RESTART_BY_USER:
  description: ""
  message: "devices/GW_RESTART_BY_USER: {self.event}"
  severity: "info"

GW_VPN_PATH_DOWN:
  description: ""
  message: "devices/GW_VPN_PATH_DOWN: {self.event}"
  severity: "info"

GW_VPN_PATH_UP:
  description: ""
  message: "devices/GW_VPN_PATH_UP: {self.event}"
  severity: "info"

GW_VPN_PEER_DOWN:
  description: ""
  message: "devices/GW_VPN_PEER_DOWN: {self.event}"
  severity: "info"

GW_VPN_PEER_UP:
  description: ""
  message: "devices/GW_VPN_PEER_UP: {self.event}"
  severity: "info"


# Marvis Events
CONNECTIVITY_TEST:
  description: "A connectivity test has been run by Marvis"
  message: "Marvis: {self.device_name} at {self.site_name}\n {self.text}"
  severity: "info"
